### ISSUE TITLE
Define depth of first soil layer used by the abiotic (etc) models based on soil model constant

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_ecosystem#348]
**Is your feature request related to a problem? Please describe.**
Currently the `soil` model defines a constant (`CoreConsts.depth_of_active_soil_layer`) which sets the depth of soil which is considered to be biogeochemically active, i.e. the depth of topsoil simulated in the `soil` model. The `abiotic`/`hydrology` models then also define soil layers separately (using config options).

@vgro pointed out that this is strange as we really want the first soil layer to correspond to the topsoil simulated by the `soil` model. At present the default options for both are set to 0.25m, but this still would allow users to select different values for the different models.

**Describe the solution you'd like**
I'm not 100% sure if we want to do this, but we could populate the topsoil layer height based on the core `depth_of_active_soil_layer` constant. This would have the advantage that the abiotic environmental information calculated for the 1st soil layer would always correspond to the layer that the `soil` model simulates. The drawback would be that this makes the system more inflexible.

**Comment by vgro** [comment]
The depth of the soil layers is defined in the core schemer and initialized by the plant model. We could add the 0.25m as an additional layer or replace it; for the `abiotic` model it does not matter what the values are.

**Comment by jacobcook1995** [comment]
I think `CoreConsts.depth_of_active_soil_layer` should be renamed `CoreConsts.depth_of_active_soil` as it isn't a layer. Then a function can be written to extract reasonable averages for soil temp and moisture for the biologically active soil.

**Comment by jacobcook1995** [comment]
This has been addressed by the introduction of a layer structure. I'm closing this issue in favour of #532 and #533, which specifically set out the cleaning up that I need to do to move the `litter` and `soil` models to use the new system
