### ISSUE TITLE
Clarify role of required init vars

### ISSUE THREAD

**Issue by vgro** [ImperialCollegeLondon/virtual_ecosystem#349]
The question came up what exactly needs to go in the `required_init_vars` of a model to ensure that the dummy simulation runs. Is it all the input variables needed to run the model or only the ones that come from somewhere external, like ERA5 data?

**Comment by davidorme** [comment]
I think we probably need to discriminate between these two things. I think this is going to be at the heart of any attempt to freeze modules - some data has to be provided to start the model running, but others are generated from those. It's linked to the idea of what variables are _provided_ by which module.

**Comment by vgro** [comment]
Ok, so I include all the inputs that the model expects to run

**Comment by davidorme** [comment]
That it needs to `__init__`. I think in the near future we may end up defining all of these variables in their own register and provide a resolution process of which variables are populated by which models and which need to be provided etc.

**Comment by davidorme** [comment]
@dalonsoa - this is linked to #371. We might want to split `required_init_vars` into `required_config_data` and `required_init_vars`? It would be useful in the variable docs to be very clear about what data _must_ be provided as an input and at the moment cannot be seen from `required_init_vars`. I guess we could work it out from `required_init_vars` and a new `vars_initialised` property across models, but it seems cleaner to be explicit!

**Comment by vgro** [comment]
resolved with #370
