### ISSUE TITLE
`xarray.open_mfdataset` can cause problems in `vr_run`

### ISSUE THREAD

**Issue by jacobcook1995** [ImperialCollegeLondon/virtual_ecosystem#354]
**Describe the bug**
Sometimes when `vr_run` is called it stalls at the point it uses `xarray.open_mfdataset()` to combine the files for individual time points into a single file. This sometimes happens on CI meaning the tests don't pass (because they don't finish). This appears to be a [known bug in `xarray`](https://github.com/pydata/xarray/issues/3961).

**To Reproduce**
By its nature it is hard to reproduce this bug but when I run `vr_run` locally (2017 MacBook Pro) it stalls ~1 in 3 times. This is more frequent than happens on the CI so I suspect the stall is somewhat spec driven.

**Approach to fix**
The bug thread suggests setting `lock=False` as a work around but suggests that this can cause errors as `hdf5` is not thread safe. I feel like stopping CI from randomly breaking is probably the top priority for now, so I think we should go ahead and set this option. If setting this option proves to be too error prone for our use case then we will need to think of an alternative way of merging data, e.g. possibly a dedicated tool for merging data

**Comment by jacobcook1995** [comment]
The actual halt is now resolved by #355, but the option may cause occasional errors. If we start seeing `HDF5` errors with any regularity then we need to revisit our solution to this issue

**Comment by davidorme** [comment]
This cropped up again and I've raised PR #457 to explicitly turn off any attempt to parallelise the file handling in `dask`. I think that is as much as we can do here - it's a problem all the way down the stack to the NetCDF code, I think.
