### ISSUE TITLE
`below canopy` layer has fixed height that might actually be above lowest `canopy` layer

### ISSUE THREAD

**Issue by vgro** [ImperialCollegeLondon/virtual_ecosystem#360]
At the moment, the vertical structure of the VR has m `soil` layers, a `surface` layer, a `below canopy` layer, n `canopy` layers, and the `above canopy` layer. All but the `canopy` layers are fixed in height throughout the simulation. The `below canopy` layer corresponds to the reference height of 1.5 m above ground. There might be cases where the lowest `canopy` layer is below this 1.5 m and layer heights no longer increase strictly monotonously. This is however a requirement for some calculations in the `abiotic` model.

Possible solutions would be dropping the `below canopy` layer and having the reference values in a separate variable or forcing the canopy layers to be above 1.5 m, but that does not allow for undergrowth.

I think this is something that is not super urgent but it is likely that we will run into errors which this at some point. Maybe this should be discussed together with #353 .

**Comment by davidorme** [comment]
That's a good catch - at least in the short term, we can guard for it in the canopy model calculations and exit if this condition is breached. If that becomes an absolute blocker, we can then address it more fully.

**Comment by vgro** [comment]
resolved with #421
