### ISSUE TITLE
Variables registry

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/virtual_ecosystem#370]
All models in the Virtual Rainforest interact through variables stored in the data object. Dependencies of one model on another model essentially boil down to needing certain variables to exist in the data object, i.e. initialized by the model in question. We’ve slightly formalised this by introducing a configuration system to order init and update methods across modules, but in the main it remains quite loosely defined. 

What would be useful would be a system that registers all variables, along with information about which module initialises them, which modules use them, and which modules updates them. This could then be used to constrain what sets of models can be run together and provide information of what variables need to be added to get a set of models to play nicely with each other. This becomes even more relevant when we have different versions of the same components, for example a simple and a mechanistic version of the abiotic model. This should also help automate the  documentation of variables used in the models, which currently documented manually. 

As a sketch: 

- Variable descriptions are created from a new ABC that defines a unique variable name along with properties like dimensionality, a description and the expected units. 
- Individual models might then specify `required_init_vars`, `updated_vars` and `required_update_vars`. A particular set of models then defines which variables need to be provided in the input data, and potentially defines solutions for the model init  and update order. 
- Creating a new Variable instance automatically adds that variable to a registry, which checks for pre-existing usage of a name. 
- It might be better to have a separate variables module, so that models then import the variable definitions that they need. That makes it easier to avoid clashes.  However, in the long-term, we want users to be able to add their own models and so these probably should be able to declare their own variables. Maybe we just need to define `Variable.__eq__` so that we can check if a variable declaration is identical?

**Comment by davidorme** [comment]
Closed by #388
