### ISSUE TITLE
add more 'theory' to the theory

### ISSUE THREAD

**Issue by vgro** [ImperialCollegeLondon/virtual_ecosystem#507]
**Is your feature request related to a problem? Please describe.**
The current 'theory' section reads more like a target than a theory.

**Describe the solution you'd like**
Our theory is more a statement along the lines of we think we can replicate complex ecosystem dynamics by focussing on the physiology of individual organisms and how that’s influenced by the abiotic environment.
Abiotic is also not really a theory – maybe add something about building on first-principles physics of energy transfer etc to replicate microclimate and hydrology.

**Comment by davidorme** [comment]
Should we replace that top level menu "Theory" title with something broader and less intimidating? Framework? Background? Ecological context?
